name: Todo CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0
          cache: 'npm'  # Enable npm caching

      - name: Install Dependencies
        run: npm install


  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build  # Ensure Build job completes first

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0
          cache: 'npm'

      - name: Install Dependencies
        run: npm install  # Leverages the cache from the Build job

      - name: Run Tests
        run: npm run lint
