name: CI/CD Pipeline

on:
  push:
    branches:
      - dev  # Run on every push to the 'dev' branch
  pull_request:
    branches:
      - main  # Run on PRs targeting the 'main' branch

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0
          cache: 'npm'

      # Step 3: Run the linter
      - name: Run Linter
        run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Tests
      - name: Run Tests
        run: npm lint

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs:
      - lint
      - test  # Ensure lint and test jobs pass first

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the application
      - name: Build Project
        run: npm run build
